apps/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('items', views.cart_items, name="cart_items"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
]

apps/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('menu', views.ProductListView.as_view(), name='product_list'),
    path('<slug:category_slug>/', views.ProductListView.as_view(), name='product_list_by_category'),
    path('menu/<int:id>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('apps.cart.urls', namespace="cart")),
    path('', include('apps.shop.urls', namespace="shop")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/cart/models.py
from django.db import models

# Create your models here.

apps/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"]),
        ]

    verbose_name = "category"
    verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Product(models.Model):
    id = models.BigAutoField(primary_key=True)
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to="products/%Y/%m/%d", blank=True, default="products/no_image.png"
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    indexes = [
        models.Index(fields=["id", "slug"]),
        models.Index(fields=["name"]),
        models.Index(fields=["-created"]),
    ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])

apps/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, initial=1, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

apps/shop/forms.py
from django import forms


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=100)
    message = forms.Textarea()

apps/cart/views.py
from django.views.generic import CreateView

from .cart import Cart
from apps.shop.models import Product
from django.contrib import messages
from .forms import CartAddProductForm
from django.views.decorators.http import require_POST
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404


class CartAddItem(CreateView):
    form_class = CartAddProductForm

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get_object(self, queryset=None):
        return Product.objects.get(id=self.kwargs["product_id"])

    def form_valid(self, form):
        cart = Cart(self.request)
        cd = form.cleaned_data
        cart.add(
            product=self.get_object(),
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
        return HttpResponse(
            messages.success(
                self.request,
                f"'{self.get_object().name}' has been added to your bag"
            )
        )


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
        return HttpResponse(messages.success(request, f"'{product.name}' has been added to your bag"))
    else:
        return HttpResponse(messages.error(request, "Item wasn't added to your bag"))


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
    # return HttpResponse(render(request, 'snippets/cartitems.html', {'cart': cart}))


def cart_items(request):
    cart = Cart(request)
    return render(request, 'snippets/cartitems.html', {'cart': cart})


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart-details.html', {'cart': cart})

apps/shop/views.py
import os
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Category, Product
from apps.cart.cart import Cart
from django.contrib import messages
from apps.cart.forms import CartAddProductForm
from apps.shop.forms import ContactForm
from django.conf import settings


class HomePageView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        cart = Cart(self.request)
        context["cart"] = cart
        return context


class ProductListView(ListView):
    template_name = "product/productslist.html"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def get_queryset(self):
        if self.kwargs:
            return Product.objects.filter(
                available=True, slug__icontains=self.kwargs["category_slug"]
            )
        else:
            return Product.objects.filter(available=True)

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        products = self.get_queryset()
        cart = Cart(self.request)

        if self.kwargs:
            category = get_object_or_404(Category, slug=self.kwargs["category_slug"])
            products = products.filter(category=category)
            context["category"] = category

        context["cart"] = cart
        context["products"] = products
        context["categories"] = Category.objects.all()

        return context


class ProductDetailView(DetailView):
    model = Product
    context_object_name = "product"
    template_name = "product/productdetail.html"
    form_class = CartAddProductForm

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    # noinspection PyUnresolvedReferences
    def get_object(self, queryset=None):
        return Product.objects.get(
            available=True, pk=self.kwargs["id"], slug=self.kwargs["slug"]
        )

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except ObjectDoesNotExist:
            raise ObjectDoesNotExist("Product not found")

        context = self.get_context_data(object=self.object, cart_form=self.form_class)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        cart = Cart(self.request)
        context["cart"] = cart
        return context

templates/cart/cart-details.html
{% extends "base.html" %}
{% load static %}


{% block title %}
	<title>
		Your Shopping Bag
	</title>
{% endblock %}

{% block content %}
	<div class="p-8 pt-12 pb-20">

		<div class="relative overflow-x-auto">

			<h1 class="font-bold text-center md:text-left text-3xl">Your Shopping Bag</h1>

			{% if cart %}
			    <table class="mt-8 w-full text-md text-left rtl:text-right text-gray-500 shadow-lg">

					<!-- Table Head -->
			        <thead class="text-md text-black uppercase bg-lime-600">
			            <tr>
			                <th scope="col" class="px-16 py-3">
			                    Image
			                </th>
			                <th scope="col" class="px-6 py-3">
			                    Product
			                </th>
			                <th scope="col" class="px-6 py-3">
			                    Quantity
			                </th>
			                <th scope="col" class="px-3 py-3">
			                    Unit Price
			                </th>
			                <th scope="col" class="px-6 py-3">
			                    Price
			                </th>
			                <th scope="col" class="px-6 py-3">
			                    Action
			                </th>
			            </tr>
			        </thead>

					<!-- Table Body -->
				    <div id="cart-items">
					    {% include 'snippets/cartitems.html' %}
				    </div>

					<!-- Table Foot -->
				    <tfoot>
			            <tr class="font-semibold uppercase text-gray-900 bg-lime-600 w-full">
			                <th scope="row" class="px-6 py-3 text-base">Total</th>
			                <td class="px-6 py-3"></td>
			                <td class="px-6 py-3 font-semibold text-lg ml-28">{{ cart|length }}</td>
			                <td class="px-6 py-3"></td>
			                <td class="px-6 py-3 font-semibold text-lg">${{ cart.get_total_price }}</td>
			                <td class="px-6 py-3"></td>
			            </tr>
			        </tfoot>
			    </table>
				{% else %}
					<div class="mt-8 p-4 text-2xl font-semibold text-center">
						You have no items in your Bag
					</div>
			{% endif %}
		</div>

		<!-- Continue Shopping, Checkout Buttons -->
		<div class="mt-12 flex flex-row justify-center">
			<a href="{% url 'shop:product_list' %}">
				<button
					type="button"
					class="text-lime-700 border-4 border-lime-700 hover:bg-lime-700 focus:ring-4 hover:border-lime-700
						   focus:outline-none focus:ring-lime-700 font-semibold rounded-sm text-lg px-5 py-2 me-2 mb-2
						   text-center bg-none hover:text-white focus:ring-offset-2 focus:bg-lime-700 focus:text-white"
				>
					Continue Shopping
				</button>
			</a>

			{% if cart %}
				<a href="#">
					<button
						type="button"
						class="text-white border-4 border-lime-700 hover:bg-lime-800 focus:ring-4 bg-lime-700 py-2
							   focus:outline-none focus:ring-lime-500 font-medium rounded-sm text-lg px-5
							   text-center me-2 mb-2 hover:border-lime-800 items-center inline-flex"
					>
						<svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							stroke-width="1.5"
							stroke="currentColor"
							class="size-6 w-5 h-5 mr-2"
						>
							<path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 0 0 2.25-2.25V6.75A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25v10.5A2.25 2.25 0 0 0 4.5 19.5Z" />
						</svg>
						Checkout
					</button>
				</a>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	<title>
		Home - Welcome to Jennifer's Kitchen
	</title>
{% endblock %}

{% block content %}
	<!-- Lime Section	-->
	<div class="h-full p-8 pt-16 pb-16 flex flex-col md:flex-row bg-lime-500">
		<div class="">
			<!-- mini Header -->
			<div class="">
				<p class="font-bold text-5xl text-lime-900 w-full text-center md:text-left">
					Home Just Got Closer
				</p>
			</div>

			<!-- max Header -->
			<div class="">
				<p
					class="mt-4 font-bold text-8xl leading-tight text-gray-900 w-full md:max-w-5xl
						   text-center md:text-left"
				>
					Exclusive Traditional Nigerian Dishes
				</p>
			</div>

			<!-- Add to Cart button -->
			<div  class="text-center md:text-left">
				<a href="{% url 'shop:product_list' %}">
					<button
						type="button"
						class="mt-14 px-10 py-6 text-white text-xl bg-lime-900 rounded-sm font-semibold
							   hover:bg-lime-800 mb-16 md:mb-0"
					>
						Have a Taste of Home
					</button>
				</a>
			</div>
		</div>

		<!-- Food Image -->
		<div class="w-96 flex items-center mx-auto mb-8 md:mb-0">
			<img
				class="w-full"
				src="{% static 'img/circle-efo-riro.png' %}"
			>
		</div>
	</div>

	<!-- Gray Section -->
	<div class="bg-gray-200 h-full p-8 md:p-14">
			<!-- Different Continent -->
			<div class="mt-8 text-center mx-auto">
				<p
					class="font-bold text-7xl leading-tight text-gray-900 w-full"
				>
					Different Continent.<br> Same Taste of Home
				</p>
			</div>

		<!-- Customer's Favorites -->
		<div class="mt-24 bg-white p-10 md:p-14">
			<div class="text-center mx-auto items-center w-full md:w-3/4 flex flex-row space-x-8">

				<!-- Star -->
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 24 24"
					fill="currentColor"
					class="size-6 w-24 h-24 text-yellow-300"
				>
					<path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z" clip-rule="evenodd" />
				</svg>


				<p
					class="font-bold text-5xl text-gray-900 w-full"
				>
					Our Customer's Favourites
				</p>

				<!-- Star -->
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 24 24"
					fill="currentColor"
					class="size-6 w-24 h-24 text-yellow-300"
				>
					<path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z" clip-rule="evenodd" />
				</svg>
			</div>

			<div class="mt-16 grid grid-cols-1 md:grid-cols-3 gap-y-12 md:gap-x-8">
				<div class="shadow-lg pb-8">
					<img
						class="w-full h-64"
						src="{% static 'img/fresh-fish-pepper-soup.jpg' %}"
					>
					<p
						class="mt-8 font-bold text-2xl text-center leading-tight text-gray-800 w-3/4 mx-auto"
					>
						Pepper Soup with Fresh Fish
					</p>
				</div>


				<div class=" shadow-lg pb-8">
					<img
						class="w-full h-64"
						src="{% static 'img/pounded-yam-egusi-4.jpg' %}"
					>
					<p
						class="mt-8 font-bold text-2xl text-center leading-tight text-gray-800 w-3/4 mx-auto"
					>
						Pounded Yam with Egusi Soup
					</p>
				</div>


				<div class=" shadow-lg pb-8">
					<img
						class="w-full h-64"
						src="{% static 'img/efo-riro-2.jpg' %}"
					>
					<p
						class="mt-8 font-bold text-2xl text-center leading-tight text-gray-900 w-3/4 mx-auto"
					>
						Efo Riro with Pounded Yam
					</p>
				</div>
			</div>

			<!-- Add to Cart button -->
			<div  class="text-center mx-auto">
				<a href="{% url 'shop:product_list' %}">
					<button
						type="button"
						class="mt-16 px-20 py-5 text-white text-xl bg-lime-900 rounded-sm font-semibold
							   hover:bg-lime-800 mb-8 md:mb-0"
					>
						Full Menu
					</button>
				</a>
			</div>
		</div>

		<!-- We Deliver -->
		<div class="mt-24 bg-yellow-400 p-16 pl-0 pb-0 flex flex-col md:flex-row">
			<div class="w-1/2 flex">
				<img
					class="w-full"
					src="{% static 'img/take-away-bag.png' %}"
				>
			</div>

			<div class="flex w-1/2 flex-col mx-auto">
				<p
					class="font-bold text-5xl text-center text-gray-900 w-full"
				>
					We Deliver
				</p>

				<p
					class="mt-8 font-semibold text-4xl text-center text-gray-900"
				>
					Satisfying Your Culinary Nostalgia just got easier
				</p>

				<p
					class="mt-8 font-normal text-2xl text-center text-gray-900"
				>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse in mi nunc.
					Morbi aliquam eros nec velit scelerisque dignissim.
				</p>

				<!-- Order Now -->
				<div  class="text-center mx-auto">
					<a href="{% url 'shop:product_list' %}">
						<button
							type="button"
							class="mt-10 px-20 py-5 text-white text-xl bg-lime-900 rounded-sm font-semibold
								   hover:bg-lime-800 mb-86 md:mb-0"
						>
							Order Now
						</button>
					</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/product/productslist.html
{% extends "base.html" %}
{% load active_link_tags %}
{% load django_htmx %}
{% load static %}

{% block title %}
	<!--suppress ALL -->


<title>
		{% if category %}
			{{ category.name }}
			{% else %}
				Products
		{% endif %}
	</title>
{% endblock %}

{% block content %}
	<div class="flex flex-col md:flex-row md:space-x-8 h-full">

		<!-- sidebar -->
		<div>
			<nav
				class="flex flex-col w-full md:w-72 px-4 tex-gray-900 bg-lime-600 text-white h-full"
			>
				<div class="font-bold text-xl mt-20">
					Categories
				</div>

				<div class="mt-4 mb-4">
					<ul class="text-lg font-semibold">
						<a href="{% url 'shop:product_list' %}">
							<button
								type="button"
								class="{% active_link 'shop:product_list' strict=True css_class='font-semibold text-white bg-lime-800 hover:bg-lime-800' %}
										px-4 py-3 hover:text-white cursor-pointer hover:bg-lime-700 font-semibold
										rounded rounded-sm w-full text-left"
							>
								All
							</button>
						</a>

						{% for c in categories %}
							<li>
								<a href="{% url 'shop:product_list_by_category' c.slug %}">
									<button
										type="button"
										hx-target="#products"
										{% if c.slug == category.slug %}
											class="mt-2 px-4 py-3 text-white border-lime-700 hover:text-white cursor-pointer
												   bg-lime-800 hover:bg-lime-800 font-semibold rounded rounded-sm
												   w-full text-left"
											{% else %}
												class="mt-2 px-4 py-3 hover:text-white cursor-pointer w-full text-left
													   hover:bg-lime-700 font-semibold rounded rounded-sm"
										{% endif %}
									>
										{{ c.name }}
									</button>
								</a>
							</li>
						{% endfor %}
					</ul>
				</div>
			</nav>
        </div>

		<!-- content -->
		<div
			id="main"
			class="w-full md:w-screen bg-none pl-8 md:pl-0 pb-12 pt-14 pr-8"
		>
			<h1 class="text-center md:text-left font-bold text-4xl md:text-3xl text-gray-800">
				{% if category %}
					{{ category.name }}
					{% else %}
						<span class="inline-flex">
							Our Delicacies
						</span>
				{% endif %}
			</h1>

			<div
				id="products"
				class="grid grid-cols-1 md:grid-cols-3 gap-y-8 md:gap-x-4 mt-12 md:mt-8 mb-8"
			>
				{% for product in products %}
					<div
						class="flex flex-col w-full border shadow-lg hover:border-lime-600 pb-8
								md:pb-6"
					>
						<a href="{{ product.get_absolute_url }}">
							<img
								class="w-full h-full md:h-60"
								src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/default.png' %}{% endif %}"
								alt="{{ product.name }}"
							>
						</a>

						<div class="mx-auto text-center mt-6 md:mt-4 font-bold w-3/4 md:w-48">
							<p class="text-gray-600 text-xl md:text-lg">
								{{ product.name }}
							</p>

							<p class="mt-4 md:mt-2 text-xl text-lime-700">
								${{ product.price }}
							</p>

							<button
								type="button"
								hx-post="{% url 'cart:cart_add' product.id %}"
								class="mt-6 md:mt-4 px-6 py-3 text-white text-lg bg-lime-700 rounded rounded-sm
									   border-lime-700 hover:bg-lime-800 inline-flex items-center"
							>
								Add to Bag
								<svg
									xmlns="http://www.w3.org/2000/svg"
									fill="none"
									viewBox="0 0 24 24"
									stroke-width="1.5"
									stroke="currentColor"
									class="size-6 text-white w-6 h-6 ml-2"
								>
									<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
								</svg>
							</button>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

templates/snippets/mobile-menu.html
{% load static tailwind_tags %}
{% load active_link_tags %}

<div
	class="hidden md:hidden bg-black"
	id="mobile-menu"
>
	<div class="flex flex-col space-y-1 p-3">

		<!-- Home -->
		<a
		    href="{% url 'shop:index' %}"
		    class="{% active_link 'shop:index' strict=True css_class='text-orange-500 hover:text-orange-500' %}
		           bg-none text-lime-600 p-3 text-lg font-semibold hover:bg-none hover:text-lime-400"
		    aria-current="page"
		>
			<!-- Home -->
			<span class="inline-flex items-center">
		        <svg
		            xmlns="http://www.w3.org/2000/svg"
		            viewBox="0 0 24 24"
		            fill="currentColor"
		            class="w-5 h-5 mr-2"
		        >
				  <path d="M11.47 3.841a.75.75 0 0 1 1.06 0l8.69 8.69a.75.75 0 1 0 1.06-1.061l-8.689-8.69a2.25 2.25 0 0 0-3.182 0l-8.69 8.69a.75.75 0 1 0 1.061 1.06l8.69-8.689Z" />
				  <path d="m12 5.432 8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 0-.75-.75h-3a.75.75 0 0 0-.75.75V21a.75.75 0 0 1-.75.75H5.625a1.875 1.875 0 0 1-1.875-1.875v-6.198a2.29 2.29 0 0 0 .091-.086L12 5.432Z" />
				</svg>
		        Home
		    </span>
		</a>

		<!-- Menu -->
		<a
		    href="{% url 'shop:product_list' %}"
		    class="{% active_link 'shop:product_list' css_class='text-orange-500 hover:text-orange-500' %}
		            bg-none text-lime-600 p-3 text-lg font-semibold hover:bg-none hover:text-lime-400"
		    aria-current="page"
		>
		    <!-- Plus icon -->
		    <span class="inline-flex items-center">
		        <svg
			        xmlns="http://www.w3.org/2000/svg"
			        viewBox="0 0 24 24"
			        fill="currentColor"
			        class="w-5 h-5 mr-2"
		        >
			        <path d="M11.25 4.533A9.707 9.707 0 0 0 6 3a9.735 9.735 0 0 0-3.25.555.75.75 0 0 0-.5.707v14.25a.75.75 0 0 0 1 .707A8.237 8.237 0 0 1 6 18.75c1.995 0 3.823.707 5.25 1.886V4.533ZM12.75 20.636A8.214 8.214 0 0 1 18 18.75c.966 0 1.89.166 2.75.47a.75.75 0 0 0 1-.708V4.262a.75.75 0 0 0-.5-.707A9.735 9.735 0 0 0 18 3a9.707 9.707 0 0 0-5.25 1.533v16.103Z" />
				</svg>
	            Menu
		    </span>
		</a>

		<!-- Sign In -->
		<a
		    href="{% url 'shop:index' %}"
		    class="{% active_link 'shop:contact' css_class='text-orange-500 hover:text-orange-500' %}
		           bg-none text-lime-600 p-3 text-lg font-semibold hover:bg-none hover:text-lime-400"
		    aria-current="page"
		>
		    <!-- User icon -->
		    <span class="inline-flex items-center">
		        <svg
			        xmlns="http://www.w3.org/2000/svg"
			        viewBox="0 0 24 24"
			        fill="currentColor"
			        class="w-5 h-5 mr-2"
		        >
					<path fill-rule="evenodd" d="M7.5 6a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM3.751 20.105a8.25 8.25 0 0 1 16.498 0 .75.75 0 0 1-.437.695A18.683 18.683 0 0 1 12 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 0 1-.437-.695Z" clip-rule="evenodd" />
				</svg>
		        Sign In
		    </span>
		</a>

		<!-- About Us -->
		<a
		    href="{% url 'shop:index' %}"
		    class="{% active_link 'shop:contact' css_class='text-orange-500 hover:text-orange-500' %}
		           bg-none text-lime-600 p-3 text-lg font-semibold hover:bg-none hover:text-lime-400"
		    aria-current="page"
		>
		    <!-- Question Mark Icon -->
		    <span class="inline-flex items-center">
		        <svg
			        xmlns="http://www.w3.org/2000/svg"
			        viewBox="0 0 24 24"
			        fill="currentColor"
			        class="w-5 h-5 mr-2"
		        >
					<path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12Zm11.378-3.917c-.89-.777-2.366-.777-3.255 0a.75.75 0 0 1-.988-1.129c1.454-1.272 3.776-1.272 5.23 0 1.513 1.324 1.513 3.518 0 4.842a3.75 3.75 0 0 1-.837.552c-.676.328-1.028.774-1.028 1.152v.75a.75.75 0 0 1-1.5 0v-.75c0-1.279 1.06-2.107 1.875-2.502.182-.088.351-.199.503-.331.83-.727.83-1.857 0-2.584ZM12 18a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z" clip-rule="evenodd" />
				</svg>
		        About Us
		    </span>
		</a>
	</div>
</div>